---
- name: Restart Docker
  ansible.builtin.systemd_service:
    name: docker
    daemon_reload: true
    state: restarted

- name: Restart JumpServer
  ansible.builtin.command: ./jmsctl.sh restart
  args:
    chdir: "/opt/jumpserver-installer-{{ jumpserver_version }}"
  no_log: true
  changed_when: true

- name: Reload JumpServer firewall
  ansible.builtin.systemd_service:
    name: nftables
    state: restarted
